values=c(as.matrix(read.table("3_2.dat")))
Pressure=c(rep(c(200,200,215,215,230,230),3))
Pressure=factor(Pressure)
Temperature=c(rep(150,6),rep(160,6),rep(170,6))
Temperature=factor(Temperature)
model=aov(values ~ Pressure*Temperature)
anova(model)
par(mfrow=c(2,1))
tukey=TukeyHSD(model,"Temperature")
tukey
#plot(tukey)
tukey=TukeyHSD(model,"Pressure")
tukey
#plot(tukey)
library(car)
leveneTest(model)
shapiro.test(residuals(model))
plot(residuals(model)[seq(1,18,by=2)],col="red",ylab="Residuals",xlab="Index")
par(new = TRUE)
plot(residuals(model)[seq(2,18,by=2)],col="blue",ylab="Residuals",xlab="Index")
plot(model$fit,model$res,ylab="Residuals",xlab="Fitted values")
#qqnorm(residuals(model))
#qqline(residuals(model))

#interaction.plot(Temperature,Pressure,values, xlab="Temperature", ylab="Yield")
kruskal.test(values ~ Pressure + Temperature)